---
csl: canadian-journal-of-fisheries-and-aquatic-sciences.csl
output:
  pdf_document: default
  html_document:
    fig_caption: yes
  word_document:
    fig_caption: yes
    pandoc_args: --smart
    reference_docx: format.docx
---

Title: Lake trout (*Savelinus namaycush*) reproductive behaviour in a northern lake

Authors: David T.Callaghan^1^*, Paul J. Blanchfield^1,2^, and Peter A. Cott^3^

^1^Department of Biological Sciences, University of Manitoba, 50 Sifton Road, Winnipeg, MB R3T 2N2, Canada
^2^ Freshwater Institute, Fisheries and Oceans Canada, 501 University Crescent, Winnipeg, MB, R3T 2N6, Canada 
^3^ Cumulative Impact Monitoring Program - Environment and Natural Resources, Government of the Northwest Territories, Box 1320, Yellowknife, Northwest Territories X1A 2L9, Canada.

*Corresponding Author Email: callagdt@myumanitoba.ca


##Abstract

This thesis investigates lake trout (*Salvelinus namaycush*) reproduction northern lakes. Lake trout have a broad distribution across Canada's North, yet most studies that describe reproductive habitat are from the southern extent of their range. I first assessed whether lake trout spawning habitat, typically characterized as wave-swept shoals with clean cobble that face predominant wind directions, is similar for a northern lake. Specifically, I examined a dozen sites around Alexie Lake, Northwest Territories, to test if physical habitat and wind exposure were important determinants of spawning site use and embryonic survival. Spawning occurred in ~2 m water depth, on 3–15 cm diameter clean substrate found on the leading edge of shoals that ended in a rock crib rising abruptly in nearshore regions around the lake. Wind direction was predominantly from the west, although it was highly variable within and among spawning seasons. I found evidence of lake trout spawning at each site examined, but not limited to shoals facing a predominate wind direction. High variation in embryonic survival (2–83%) from incubation trays was observed among spawning sites, suggesting a large gradient in habitat quality exists within a given lake. Modelled wind exposure did not predict embryonic survival, nor did physical characteristics that may influence interstitial water flow on spawning shoals. 
  I also provide a detailed description of the lake trout mating system at the whole lake scale in a typical northern boreal lake. Using an acoustic telemetry monitoring system and a novel spatial temporal clustering analysis, I was able to quantify lake trout spawning movements and behaviours over the course of an entire spawning season. Lake trout were found to cluster on spawning shoals virtually around the entire nearshore region of Alexie Lake, as well as around several islands, which appears to further confirm previous findings that subtable spawning habitat is abundant in Alexie Lake. Males arrived earlier than females and spent longer durations on spawning shoals over the course of the spawning season. Males formed >4 times as many spawing clusters and visited more sites than females. Spawning clusters predominantly were formed at night but were also observed during daylight hours, especially during the peak spawning season. I found males may exert more energy than females during the spawning season, with males showing higher activity rates and longer periods spent on spawning shoals than females, in spite of similar daily travel distances between sexes. Overall, females performed more linear movements over the course of the spawning season suggesting a searching behaviour, while males were less persitent and more random in there movements. Our findings challenge the conventional role of wind as a predominant predictor of lake trout spawning site quality. We propose that the unpredictable nature of wind and abundance of suitable habitat may favour lake-wide spawning by lake trout as a bet-hedging strategy in northern lakes with limited fetch.

##Introduction  

  The evolution of animal mating systems is mainly influenced by sexual selection [@andersson_sexual_1994], parental care [@trivers_parental_1972] and the spatial temporal distribution of resources and mates [@emlen_ecology_1977]. In many species, males optimize their fitness by mating with multiple females. By contrast, the optimal mating rate of females is limited by the production of progeny per mating event [@bateman_intra_1948]. This high energetic investment in gametes by females relative to males often results in conventional sex roles, whereby females provide parental care and males compete for access to females [@kokko_parental_2008]. Because parental care is uncommon in fishes [only found in 21% of families; @blumer_bibliography_1982], their mating systems are ultimately shaped by the distribution of resources necessary for each sex to ensure successful reproduction [@emlen_ecology_1977].  
  
Salmonine fishes (salmons, trouts and chars) are typically observed in a site-based competitive mating system where males compete for access to females, which is thought to be the limiting resource [@gross_sunfish_1984], while females compete for territories to establish and prepare their spawning sites [@fleming_pattern_1998]. Females construct a nest (a series of pits termed a redd) and deposit eggs that are fertilized externally by one or more males. Limited numbers of suitable spawning sites and variability in spawning site quality results in females becoming very selective when choosing their nest sites [@blanchfield_relative_2005; @esteve_observations_2005; @degaudemar_sexual_1998]. Males will fight for proximity to females, with body size and exagerated body shape being the main factors in establishing dominance hierarchies [@fleming_breeding_1994; @quinn_effects_1994]. Paternity tests have shown that the closest male to the female generally fertilizes the greatest proportion of eggs [@blanchfield_breeding_2003; @mjolnerod_mate_1998], thus proximity to females increases fertilization success. As a result, male reproductive success is maximized quantitatively, by mating with as many females as possible; whereas female reproductive success is maximized qualitatively, by choosing high quality nest sites and males  [@degaudemar_sexual_1998].  

  The reproductive behaviours of lake trout (*Salvelinus namaycush*) sharply contrasts the typical salmonine mating system described above [@gunn_spawning_1995; @esteve_lake_2008; @muir_lake_2012]. Spawning usually takes place in lakes on waveswept shoals, and unlike all other salmonines, lake trout do not provide any parental care [i.e., no redd is constructed by the female; @martin_lake_1980]. Eggs are spawned directly onto clean substrate, where they fall into interstitial spaces and incubate for several months before emerging [@royce_breeding_1951]. Lake trout also do not displayovert male-male agonistic behaviour [@royce_breeding_1951; @gunn_spawning_1995; @esteve_lake_2008], a predominant behavioural characteristic of the Salmoninae subfamily [@esteve_observations_2005]. Further, females do not show territorial behaviour (i.e. redd defence) or obvious mate selection [@esteve_lake_2008]. However, some similarities do occur in mating behaviour between lake trout and other salmonines, including males arriving earlier on breeding grounds and staying longer than females each year [@miller_observations_1948; @royce_breeding_1951; @martin_lake_1980; @muir_lake_2012]. In the absence of a site-based competitive mating system and parental care, mating system theory predicts that female reproductive success is driven by habitat quality and mate selection, whereas male reproductive success should be driven by spawning frequency [@degaudemar_sexual_1998]. 
  
  Lake trout (*Salvelinus namaycush*) are a long lived, iteroparous species that typically spawn in lakes during the fall [@gunn_spawning_1995]. Migration from the offshore summer refuge onto nearshore spawning shoals generally coincides with surface water temperatures declining to 12&deg; C or lower [@redick_review_1967]. Preferred spawning habitat is selected along exposed shorelines off points, islands or on mid-lake shoals containing clean substrate including pebble and cobble mainly 3-15 cm in diameter [@martin_lake_1980; See Chapter 2]. Spawning predominately occurs during night time [@gunn_spawning_1995] but has been observed during the day [@esteve_lake_2008; @muir_lake_2012; @binder_new_2015]. Males often constitute 60–85% of annual spawning populations,,, resulting in highly skewed sex ratios on spawning shoals. This imbalance is thought to be a product of earlier maturation, early arrival and longer duration on spawning grounds and the increased likelihood of males spawning each year [@miller_observations_1948; @eschmeyer_reproduction_1955; @martin_reproduction_1957].

  Lake trout reproductive behaviour is relatively understudied when compared to other salmonines, and what literature exists is largely from the southern extent of it's geographic range [@muir_lake_2012]. In general, information on the timing of movement onto spawning shoals and the degree of movements among spawning sites for males and females at seasonal and daily scales remains an important knowledge gap. Furthermore, few studies have investigated reproductive strategies of lake trout [@esteve_lake_2008; @muir_lake_2012]. 
  
The objectives of this manuscript is three-fold: (i) to determine when and where lake trout spawn in a typical northern boreal lake; (ii) to describe sex-specific timing and movements of lake trout over the duration of a spawning season; and (iii) to test whether male and female lake trout employ a bet-hedging strategy by spawning on multiple sites. Using data collected from a whole-lake acoustic telemetry array, I will present the movements of five male and six female lake trout over the course of the 2013 spawning season. A spatial temporal clustering analysis was used to determine when and where lake trout formed spawning clusters. These data reveal new insights into the reproductive strategies of male and female lake trout and further our knowledge on spawning site use for managing this iconic Canadian fish species.
  
##Methods  

##References