---
title: "summary"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo=FALSE, message=FALSE, warning=FALSE)
library(printr)
library(knitr)
library(dplyr)
load("SpawnClust.RData")
```

## Cluster Parameters

```{r cluster_params}

kable(cluster[,c(1,2,4,8,12)])
```

## Cluster Frequency over time


```{r spawn_time, fig.height=11, fig.width= 8.5}



spawn.num.12<-spawn.num[spawn.num$YEAR==2012,]
spawn.num.13<-spawn.num[spawn.num$YEAR==2013,]
spawn.num.14<-spawn.num[spawn.num$YEAR==2014,]


peakdates<-function(date,freq){
  data<-data.frame(DATE=date,
                    FREQ=freq)
  peak<-data.frame(START=min(data$DATE[data$FREQ>=(max(data$FREQ)/2)]),
                   END=max(data$DATE[data$FREQ>=(max(data$FREQ)/2)]))
  
}

peakdates.12<-peakdates(date=spawn.num.12$DATE,freq=spawn.num.12$FREQ)
peakdates.13<-peakdates(date=spawn.num.13$DATE,freq=spawn.num.13$FREQ)
peakdates.g13<-peakdates(date=spawn.num.13$DATE,freq=spawn.num.13$FREQ13)
peakdates.14<-peakdates(date=spawn.num.14$DATE,freq=spawn.num.14$FREQ) 
peakdates.g14<-peakdates(date=spawn.num.14$DATE,freq=spawn.num.14$FREQ14)

par(mfrow=c(3,1))

#2012
plot(FREQ/24~DATE,data=spawn.num.12,ylim=c(0,3),
     xlim=as.POSIXct(c("2012-08-15","2012-10-15"),format="%Y-%m-%d", tz="MST"),type="h",col="grey",
     lwd=6,lend=2)
lines(c(peakdates.12$START-12*60*60,peakdates.12$START-12*60*60),c(-1,3.5))
lines(c(peakdates.12$END+12*60*60,peakdates.12$END+12*60*60),c(-1,3.5))

#2013 group 2013
plot(FREQ13/9~DATE,data=spawn.num.13,ylim=c(0,3),
     xlim=as.POSIXct(c("2013-08-15","2013-10-15"),format="%Y-%m-%d", tz="MST"), type="h",col="grey",
     lwd=6,lend=2)
lines(c(peakdates.g13$START-12*60*60,peakdates.g13$START-12*60*60),c(-1,3.5))
lines(c(peakdates.g13$END+12*60*60,peakdates.g13$END+12*60*60),c(-1,3.5))

#2014 group 2014
plot(FREQ14/3~DATE,data=spawn.num.14,ylim=c(0,3),
     xlim=as.POSIXct(c("2014-08-15","2014-10-15"),format="%Y-%m-%d", tz="MST"),type="h",col="grey",
     lwd=6,lend=2)
lines(c(peakdates.g14$START-12*60*60,peakdates.g14$START-12*60*60),c(-1,3))
lines(c(peakdates.g14$END+12*60*60,peakdates.g14$END+12*60*60),c(-1,3))



par(mfrow=c(1,1))


```

##Spawning Shoal Use

```{r }


library(mapplots)
library(maptools)
library(scales)


data<-first.clust
xyz<-make.xyz(x=data$CLUST.X,y=data$CLUST.Y,z=data$FREQ,group=data$YEAR)

plot(shore_outline)
  
draw.pie(z=xyz$z, x=xyz$x, y=xyz$y, 
        radius=100, col=c(alpha("#FFEF00", 0.7),alpha("#AEC6CF", 0.7),alpha("#FF6961", 0.7)),
        border=c(alpha("#FFEF00", 1),alpha("#AEC6CF", 1),alpha("#FF6961", 1))) 

text(650800,6954500, "Year",font=2) 
legend.pie(650800,6954300, labels=c("2012","2013","2014"), radius = 100,
           bty="n", col=c(alpha("#FFEF00", 0.7),alpha("#AEC6CF", 0.7),alpha("#FF6961", 0.7)),
           border=c(alpha("#FFEF00", 1),alpha("#AEC6CF", 1),alpha("#FF6961", 1)),
           label.dist=1.7)

text(650800,6954000, "Frequency",font=2) 
legend.bubble(650800,6953800, z=92, round=1, n=1, maxradius=100, bty="n",txt.col="transparent")
text(650950,6953800, "92", cex=0.8) 
legend.bubble(650800,6953625, z=46, round=1, n=1, maxradius=50, bty="n",txt.col="transparent")
text(650900,6953625, "46", cex=0.7) 
legend.bubble(650800,6953525, z=23, round=1, n=1, maxradius=25, bty="n",txt.col="transparent")
text(650875,6953525,"23", cex=0.6) 
legend.bubble(650800,6953462, z=12, round=1, n=1, maxradius=13, bty="n",txt.col="transparent")
text(650862,6953462, "12", cex=0.5)               



#determine max frequency
max.all<-max(first.clust$FREQ)

#2012
data<-filter(first.clust,YEAR==2012)
#determine scaling factor
s=max(data$FREQ)/max.all

plot(shore_outline, main=data$YEAR[1], col="grey90",border="grey70")

draw.bubble(z=data$FREQ, x=data$CLUST.X, y=data$CLUST.Y, 
         maxradius=200*s, col=alpha("pink", 0.3),pch=19)
draw.bubble(z=data$FREQ, x=data$CLUST.X, y=data$CLUST.Y, 
            maxradius=200*s, col=alpha("red",0.3))


legend.bubble(650800,6954000, z=max.all, round=1, n=3, maxradius=200, bty="n",pch=19,
              col=alpha("pink",0.3), txt.cex = 0.7, txt.col="transparent")
legend.bubble(650800,6954000, z=max.all, round=0, n=3, maxradius=200, bty="n",
              col=alpha("red",0.3),txt.cex = 0.7, txt.col = alpha("red",0.3))


#2013
data<-filter(first.clust,YEAR==2013)
#determine scaling factor
s=max(data$FREQ)/max.all
plot(shore_outline, main=data$YEAR[1], col="grey90",border="grey70")

draw.bubble(z=data$FREQ, x=data$CLUST.X, y=data$CLUST.Y, 
            maxradius=200*s, col=alpha("pink", 0.3),pch=19)
draw.bubble(z=data$FREQ, x=data$CLUST.X, y=data$CLUST.Y, 
            maxradius=200*s, col=alpha("red",0.3))


legend.bubble(650800,6954000, z=max.all, round=1, n=3, maxradius=200, bty="n",pch=19,
              col=alpha("pink",0.3), txt.cex = 0.7, txt.col="transparent")
legend.bubble(650800,6954000, z=max.all, round=0, n=3, maxradius=200, bty="n",
              col=alpha("red",0.3),txt.cex = 0.7, txt.col = alpha("red",0.3))


#2014
data<-filter(first.clust,YEAR==2014)
#determine scaling factor
s=max(data$FREQ)/max.all

plot(shore_outline, main=data$YEAR[1], col="grey90",border="grey70")

draw.bubble(z=data$FREQ, x=data$CLUST.X, y=data$CLUST.Y, 
            maxradius=200*s, col=alpha("pink", 0.3),pch=19)
draw.bubble(z=data$FREQ, x=data$CLUST.X, y=data$CLUST.Y, 
            maxradius=200*s, col=alpha("red",0.3))


legend.bubble(650800,6954000, z=max.all, round=1, n=3, maxradius=200, bty="n",pch=19,
              col=alpha("pink",0.3), txt.cex = 0.7, txt.col="transparent")
legend.bubble(650800,6954000, z=max.all, round=0, n=3, maxradius=200, bty="n",
              col=alpha("red",0.3),txt.cex = 0.7, txt.col = alpha("red",0.3))

data<-table(ltspawnclust$YEAR,ltspawnclust$SITE)
data<-data[,order(colSums(data))]
barplot(data,
        axes=FALSE,
        xlim=c(0,100),
        xlab="Total Spawning Clusters Formed",
        ylab="Spawning Sites",
        axisnames=FALSE,
        horiz=TRUE,
        col=c(alpha("#FFEF00", 1),alpha("#AEC6CF", 1),alpha("#FF6961", 1)),
        border=c(alpha("#FFEF00", 1),alpha("#AEC6CF", 1),alpha("#FF6961", 1)),
        legend.text=TRUE,
        args.legend=list( y=145, 
                          x=65, 
                          bty = "n",
                          xpd=TRUE,
                          horiz=TRUE,
                          border="white")
        )
axis(1,pos=0)

  
```

```{r}
data<-spawntable[spawntable$MONTH==9,]
data$ACCEL.SD[is.nan(data$ACCEL.SD)]<-"-"
data$ACCEL.MEAN[is.nan(data$ACCEL.MEAN)]<-"-"
kable(data)
```
```{r, echo=FALSE, messages=FALSE, cache=FALSE}

#format scientific notation

require(lubridate)
#select only males or females
data<-daily[daily$MONTH==9 & (daily$SEX=="M" | daily$SEX=="F") & daily$TRANSMITTER!="LT-32",]
data$DAY<-day(as.Date(data$DATE))
data$YEAR<-as.factor(data$YEAR)
data$TRANSMITTER<-as.factor(data$TRANSMITTER)
data$SEX<-as.factor(data$SEX)
#centre days
data$cDAY<-data$DAY-mean(data$DAY)


############################

#daily displacement

require(nlme)
require(MuMIn)
require(lattice)
require(car)
require(lsmeans)
library(effects)
```
```{r}
xyplot(sqrt(STEPLENGTH) ~ DAY|TRANSMITTER, groups=SEX, type=c("p","smooth"), data=data)

```
```{r}
#test if random effect better than linear regression
#linear model
gls1<-gls(sqrt(STEPLENGTH)~SEX+DAY+I(DAY^2)+YEAR,data=data)
#mixed effects model
mod1<-lme(sqrt(STEPLENGTH)~SEX+DAY+I(DAY^2)+YEAR, random=~1|TRANSMITTER,data=data, method="REML")

#check variance inflation factor
#vif(mod1)
#centre days
data$cDAY<-data$DAY-mean(data$DAY)

#linear model
gls1<-gls(sqrt(STEPLENGTH)~SEX+cDAY+I(cDAY^2)+YEAR,data=data)
#mixed effects model
mod1<-lme(sqrt(STEPLENGTH)~SEX+cDAY+I(cDAY^2)+YEAR, random=~1|TRANSMITTER,data=data, method="REML")
#re-check variance inflation factor
#vif(mod1)

#test is random effects improves model
#anova(gls1,mod1)#random effect better model,

#acf(residuals(mod1, type="normalized"))#looks like correlation

#add AR1 correlation structure to model
mod2<-lme(sqrt(STEPLENGTH)~SEX+cDAY+I(cDAY^2)+YEAR, random=~1|TRANSMITTER, correlation=corAR1(form=~1|TRANSMITTER/YEAR) ,data=data, method="REML")

#the AR1 model is a better fit then the model without the correlation structure
#anova(mod1,mod2)

#re-check autocorrelation
#acf(residuals(mod2, type="normalized"))#looks pretty good


#re-run model 2 with maximum likelihood (ML)
mod2<-lme(sqrt(STEPLENGTH)~SEX+cDAY+I(cDAY^2)+YEAR, random=~1|TRANSMITTER, correlation=corAR1(form=~1|TRANSMITTER/YEAR) ,data=data, method="ML")

#summary(mod2)


#drop SEX
#mod2.a<-update(mod2,.~.-SEX)
#check significance of SEX
#anova(mod2,mod2.a)# looks to be insignificant and can be dropped from full model


#drop DAY
#mod2.b<-update(mod2,.~.-cDAY)
#check significance of DAY
#anova(mod2,mod2.b)# significant!

#drop DAY^2
#mod2.c<-update(mod2,.~.-I(cDAY^2))
#check significance of DAY^2
#anova(mod2,mod2.c)# significant!


#drop YEAR
#mod2.d<-update(mod2,.~.-YEAR)
#Check significance of YEAR
#anova(mod2,mod2.d)# significant difference



#full model
mod.dd<-mod2
Anova(mod.dd,type=2)
#r.squaredGLMM(mod.dd)

plot(allEffects(mod.dd))
#check assumptions
#heterogeneity
#plot(fitted(mod.dd), residuals(mod.dd, type="normalized"), xlab = "Fitted Values", ylab = "Residuals")
#abline(h = 0, lty = 2)
#lines(smooth.spline(fitted(mod.dd), residuals(mod.dd, type="normalized")),col="red")
#normality
#hist(residuals(mod.dd,type="normalized"))
#independence
#acf(residuals(mod.dd,type="normalized"))


```


```{r}

####Persistence Index

#hist(data$PERSINDEX)


#boxplot(PERSINDEX~SEX*YEAR,data=data)
xyplot(PERSINDEX ~ DAY|TRANSMITTER, groups=YEAR, type= c("p","smooth"), data=data)


#test if random effect better than linear regression
#linear model
gls1<-gls(PERSINDEX~SEX+cDAY+I(cDAY^2)+YEAR,data=data)
#mixed effects model
mod1<-lme(PERSINDEX~SEX+cDAY+I(cDAY^2)+YEAR, random=~1|TRANSMITTER,data=data, method="REML")

#check variance inflation factor
#vif(mod1)
#anova(gls1,mod1)#random effect better model,
#l.ratio<-anova(gls1,mod1)[[2,"L.Ratio"]] 
#0.5*(1-pchisq(l.ratio,1))
#check for autocorrelation
#acf(residuals(mod1, type="normalized"))#looks like correlation

#add AR1 correlation structure to model
mod2<-lme(PERSINDEX~SEX+cDAY+I(cDAY^2)+YEAR, random=~1|TRANSMITTER, correlation=corAR1(form=~1|TRANSMITTER/YEAR) ,data=data, method="REML")


#the AR1 model is a better fit then the model without the correlation structure
#anova(mod1,mod2)

#re-check autocorrelation
#acf(residuals(mod2, type="normalized"))#looks pretty good

mod2<-lme(PERSINDEX~SEX+cDAY+I(cDAY^2)+YEAR, random=~1|TRANSMITTER, correlation=corAR1(form=~1|TRANSMITTER/YEAR) ,data=data, method="ML")


#summary(mod2)


#drop SEX
#mod2.a<-update(mod2,.~.-SEX)
#check significance of SEX
#anova(mod2,mod2.a)# significant


#drop DAY
#mod2.b<-update(mod2,.~.-cDAY)
#check significance of DAY
#anova(mod2,mod2.b)# significant!

#drop DAY^2
#mod2.c<-update(mod2,.~.-I(cDAY^2))
#check significance of DAY^2
#anova(mod2,mod2.c)# insignificant


#drop YEAR
#mod2.d<-update(mod2,.~.-YEAR)
#Check significance of YEAR
#anova(mod2,mod2.d)# significant difference


#best model

mod.pi<-mod2
#r.squaredGLMM(mod.pi)

Anova(mod.pi,type=2)
plot(allEffects(mod.pi))

#check assumptions
#heterogeneity
#plot(fitted(mod.pi), residuals(mod.pi, type="normalized"), xlab = "Fitted Values", ylab = "Residuals")
#abline(h = 0, lty = 2)
#lines(smooth.spline(fitted(mod.pi), residuals(mod.pi, type="normalized")),col="red")
#normality
#hist(residuals(mod.pi,type="normalized"))
#independence
#acf(residuals(mod.pi,type="normalized"))

```
```{r}

###Acceleration

#accelerometers not available in 2012
data.ac<-data[data$YEAR!=2012,]
data.ac$YEAR<-droplevels(data.ac$YEAR)
#remove fish without accelerometers
data.ac<-data.ac[!is.na(data.ac$ACCELMEAN),]

#hist(data.ac$ACCELMEAN)
#log transform for normality
#hist(log(data.ac$ACCELMEAN))
#boxplot(log(ACCELMEAN)~SEX,data.ac)
```
```{r}
xyplot(log(ACCELMEAN) ~ DAY|TRANSMITTER, group=YEAR, type= c("p", "smooth"), data=data.ac)


#test if random effect better than linear regression
#linear model
gls1<-gls(log(ACCELMEAN)~SEX+cDAY+I(cDAY^2)+YEAR,data=data.ac)
#mixed effects model
mod1<-lme(log(ACCELMEAN)~SEX+cDAY+I(cDAY^2)+YEAR, random=~1|TRANSMITTER,data=data.ac, method="REML")

#check variance inflation
#vif(mod1)

#anova(gls1,mod1)#random effect better model, 

#check for autocorrelation
#acf(residuals(mod1, type="normalized"))#looks like correlation

#add AR1 correlation structure to model
mod2<-lme(log(ACCELMEAN)~SEX+cDAY+I(cDAY^2)+YEAR, random=~1|TRANSMITTER, correlation=corAR1(form=~1|TRANSMITTER) ,data=data.ac, method="REML")

#the AR1 model is a better fit then the model without the correlation structure
#anova(mod1,mod2)

#re-check autocorrelation
#acf(residuals(mod2, type="normalized"))#looks pretty good

mod2<-lme(log(ACCELMEAN)~SEX+cDAY+I(cDAY^2)+YEAR, random=~1|TRANSMITTER, correlation=corAR1(form=~1|TRANSMITTER) ,data=data.ac, method="ML")

#test significance of intereaction
#mod2.a<-update(mod2,.~.-SEX)# drop interaction
#anova(mod2,mod2.a)#not significant remove

#mod2.b<-update(mod2,.~.-cDAY)# drop interaction
#anova(mod2,mod2.b)#not significant remove

#mod2.c<-update(mod2,.~.-I(cDAY^2))# drop interaction
#anova(mod2,mod2.c)#not significant remove

#mod2.d<-update(mod2,.~.-YEAR)# drop interaction
#anova(mod2,mod2.d)
#not significant remove
#best model



mod.ac<-mod2
#mod.ac<-update(mod.ac,.~.-YEAR)

#r.squaredGLMM(mod.ac)
Anova(mod.ac,type=2)
#check assumptions
#heterogeneity
#plot(fitted(mod.ac), residuals(mod.ac, type="normalized"), xlab = "Fitted Values", ylab = "Residuals")
#abline(h = 0, lty = 2)
#lines(smooth.spline(fitted(mod.ac), residuals(mod.ac, type="normalized")),col="red")
#normality
#hist(residuals(mod.ac,type="normalized"))
#independence
#acf(residuals(mod.ac,type="normalized"))


plot(allEffects(mod.ac))


 ```




